spring:
    datasource:
        url: jdbc:h2:mem:booking
        username: admin
        password: password
    h2:
        console:
            enabled: true
server:
    port : 3010

authentication:
    token:
        name: AuthToken