export enum AccommodationType {
  SZALLODA = "SZALLODA",
  PANZIO = "PANZIO",
  KEMPING = "KEMPING",
  UDOLOHAZ = "UDOLOHAZ",
  EGYEB_SZALLASHELY = "EGYEB_SZALLASHELY",
  MAGANSZALLASHELY = "MAGANSZALLASHELY"
}